# Generated by Django 5.0.2 on 2026-06-02 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_latitude_property_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'booking_property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='propertyreview',
            old_name='property',
            new_name='booking_property',
        ),
        migrations.AddField(
            model_name='property',
            name='access_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='airbnb_listing_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_com_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='maximum_nights',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_nights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('str', 'Short-Term Rental'), ('ltr', 'Long-Term Rental'), ('both', 'Both')], default='str', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='weekly_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='propertyreview',
            unique_together={('booking_property', 'user')},
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('suite', 'Suite'), ('villa', 'Villa'), ('cottage', 'Cottage')], default='room', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_occupancy', models.PositiveIntegerField(default=2)),
                ('num_beds', models.PositiveIntegerField(default=1)),
                ('num_bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_private_bathroom', models.BooleanField(default=True)),
                ('amenities', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('booking_property', 'name')},
            },
        ),
    ]
