# Generated by Django 5.0.2 on 2026-06-02 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0005_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(help_text='Payer or payee name', max_length=200)),
                ('entry_type', models.CharField(choices=[('receipt', 'Receipt (Income)'), ('payment', 'Payment (Expense)')], max_length=10)),
                ('category', models.CharField(choices=[('room_booking', 'Room Booking'), ('management_fee', 'Management Fee'), ('other_income', 'Other Income'), ('rent_expense', 'Rent/Lease'), ('internet', 'Internet'), ('cleaning', 'Cleaning'), ('supplies', 'Supplies'), ('furniture', 'Furniture & Equipment'), ('maintenance', 'Maintenance & Repairs'), ('salary', 'Salary/Wages'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('other_expense', 'Other Expense')], default='room_booking', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_opening_balance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='bookings.booking')),
                ('booking_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='properties.property')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashbook Entry',
                'verbose_name_plural': 'Cashbook Entries',
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('property_name', models.CharField(max_length=200)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_nights', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='bookings.booking')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('category', models.CharField(choices=[('room_booking', 'Room Booking'), ('management_fee', 'Management Fee'), ('other_income', 'Other Income'), ('rent_expense', 'Rent/Lease'), ('internet', 'Internet'), ('cleaning', 'Cleaning'), ('supplies', 'Supplies'), ('furniture', 'Furniture & Equipment'), ('maintenance', 'Maintenance & Repairs'), ('salary', 'Salary/Wages'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('other_expense', 'Other Expense')], max_length=30)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='properties.property')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('booking_property', 'period_start', 'period_end', 'category')},
            },
        ),
    ]
