# Generated by Django 5.0.2 on 2026-06-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='booking_property',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertyinquiry',
            old_name='booking_property',
            new_name='property',
        ),
    ]
