# Generated by Django 5.0.2 on 2026-06-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_booking_property_conversation_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyinquiry',
            old_name='property',
            new_name='booking_property',
        ),
    ]
