# Generated by Django 5.0.2 on 2026-06-02 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0005_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('auto_confirm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_config', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Airbnb Property',
                'verbose_name_plural': 'Airbnb Properties',
            },
        ),
        migrations.CreateModel(
            name='BookingComProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('auto_confirm', models.BooleanField(default=False)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookingcom_config', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingcom_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking.com Property',
                'verbose_name_plural': 'Booking.com Properties',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('action', models.CharField(choices=[('fetch_reservation', 'Fetch Reservation'), ('confirm_reservation', 'Confirm Reservation'), ('cancel_reservation', 'Cancel Reservation'), ('send_message', 'Send Message'), ('sync_availability', 'Sync Availability'), ('send_receipt', 'Send Receipt'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('pre_arrival', 'Pre-Arrival Instructions'), ('check_in_instructions', 'Check-in Instructions'), ('checkout_reminder', 'Checkout Reminder'), ('review_request', 'Review Request'), ('receipt', 'Receipt'), ('payment_reminder', 'Payment Reminder'), ('welcome', 'Welcome Message'), ('farewell', 'Farewell Message'), ('general', 'General')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, help_text='Used for email subject', max_length=200)),
                ('body', models.TextField(help_text='Use {{guest_name}}, {{check_in_date}}, {{check_out_date}}, {{property_name}}, {{booking_reference}}, {{total_amount}}, {{room_rate}}, {{wifi_name}}, {{wifi_password}}, {{access_instructions}}')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('meta_cloud', 'Meta Cloud API')], default='twilio', max_length=20)),
                ('account_sid', models.CharField(blank=True, max_length=200)),
                ('auth_token', models.CharField(blank=True, max_length=200)),
                ('from_number', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_configs', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
